name: Hadolint
on:
  push:
  pull_request:
  schedule:
    - cron: '0 20 * * *'

jobs:
  scan:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - uses: hadolint/hadolint-action@v3.3.0
        name: Lint hadolint
        with:
          dockerfile: Dockerfile
          format: 'sarif'
          output-file: 'hadolint-results.sarif'
      - name: Upload hadlint scan results to GitHub Security tab
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'hadolint-results.sarif'
          category: 'hadolint'
