name: Hadolint
on:
  push:
  pull_request:
  schedule:
    - cron: '0 20 * * *'

jobs:
  scan:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: hadolint/hadolint-action@v3.1.0
        name: Lint hadolint
        with:
          dockerfile: Dockerfile
          format: 'sarif'
          output-file: 'hadolint-results.sarif'
      - name: Upload hadlint scan results to GitHub Security tab
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'hadolint-results.sarif'
          category: 'hadolint'
